version: '3.8'

services:
  frontend:
    container_name: frontend_container
    image: jeralsandeeptha/bconic-frontend:1fec3c745021877180efd0047ee9e7a2a480d1d4
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    container_name: backend_container
    image: jeralsandeeptha/bconic-backend:7b6909819a3a12ff4e6d6e53a07476807ae40f32
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://jeral:1234@database_container:5432/bconic_db
      - PORT=5000
      - JWT_SECRET=secret
      - POSTGRES_USER=jeral
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bconic_db
    restart: always
  postgres:
    container_name: database_container
    image: postgres:13
    environment:
      - POSTGRES_USER=jeral
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bconic_db
    ports:
      - "5432:5432"
    volumes:
      - ./docker_volumes/postgres:/var/lib/postgresql/data
  pgAdmin:
    container_name: pgAdmin_container
    image: elestio/pgadmin:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=jeral@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
    ports:
      - "5433:80"
    depends_on:
      - postgres